### PR TITLE
Add paragraphs to receipt

### PR DESCRIPTION
**Pull request by SeriousMatt**

### CODE REVIEW

**Review by PaulNel — APPROVED** [review]

**Review by mcdurdin — APPROVED** [review]

**Comment by SeriousMatt** [comment]
@mcdurdin I restored this branch because deleting it caused a deployment failure. It's better to wait until the deployment is finished before deleting branches.

**Comment by mcdurdin** [comment]
> @mcdurdin I restored this branch because deleting it caused a deployment failure. It's better to wait until the deployment is finished before deleting branches.

That's bizarre and seriously fragile -- not keen to continue with a deployment that has dependencies like this!

Can you explain to me why the branch is needed for deployment -- we certainly don't need to do anything like this for our other sites which deploy just fine when we delete the PR branch? I can't see why anything other than `master` branch is all that is needed.

**Comment by SeriousMatt** [comment]
Yeah….I agree. Let’s scrap it first chance we get :) . What deployment pipeline are you using for the other sites again? (Kudu? Pipelines? Etc)  Not sure why the branch was needed, just saw that Azure was missing both the branch title and commit message in the deployment center, which differed from the other successful deployments. I wish there was more behind the scenes we could view there…have I mentioned I am way more familiar with AWS?

-Matt

**Comment by mcdurdin** [comment]
We use Kudu. So not sure what is going on there?

**Comment by SeriousMatt** [comment]
I took a look at the deployment again and it's basically assuming a fresh
installation of the application each time it runs. To save some time in
deployment, we can take out some of the steps that would not be necessary
each time (f.e. npm install). Do you have any kind of flag in your other
projects using kudu that only runs steps in certain scenarios (if
node_modules folder exists)? That might be helpful.

**Comment by mcdurdin** [comment]
No, we don't do anything like that with Kudu, however, we don't use Node on any of our other sites. I personally would prefer to always run `npm install` in deployment because guessing if we need to or not is a little dangerous.

**Pull request merged**
